### ISSUE TITLE
Find should give an option to not include children

### ISSUE THREAD

**Issue by manuel-bossard** [dylanroscover/jsonifier#1]
I just want to save my root's project parameters: I include the path /myproject, but all the children and children of children are included.

Ideally to /myproject only includes myproject, /myproject/* includes its children

**Comment by dylanroscover** [comment]
@nabz1337 Great idea! This is a very useful RFE, thanks for sharing. I added a recursive toggle and a few other tweaks/improvements to 0.4.0, just committed.

**Comment by manuel-bossard** [comment]
dope
When I targeted my project, all the nodes of the project got exposed and it broke my tdnetwork, it would not work anymore. I noticed that when tracking too many operators, the FPS was drastically affected, maybe by the big amount of parexec_jsonifier checking for all the parameters cooking?! 

Anyway, that recursive toggle is a great addition! Thank you for the fix!

**Comment by dylanroscover** [comment]
Yeah, if you disable "Keep Par Vals Up-to-date," that should help avoid those sorts of performance issues, especially if a bunch of pars are getting re-written at once (transition/noise floats are notorious for this...).

I suppose another nice-to-have feature would be a toggle column on the Lister table that allows per-COMP par val updating, so only specific COMPs can be updated, rather than just the global on-off switch.
